/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pseudorandomsequencevisualizer;

import java.util.AbstractQueue;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Queue;
import java.util.Stack;

/**
 *
 * @author jguty
 */
public class Visualizer extends javax.swing.JFrame {

    /**
     * Creates new form Visualizer
     */
    public Visualizer() {
        this.originator = new PseudoRandomGenerator(0);
        this.history = new Stack<>();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberLabel = new javax.swing.JLabel();
        seedEntry = new javax.swing.JTextField();
        SeedLabel = new javax.swing.JLabel();
        setSeedButton = new javax.swing.JButton();
        nextPseudoRandomButton = new javax.swing.JButton();
        previousPseudoRandom = new javax.swing.JButton();
        TitleLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numberLabel.setBackground(new java.awt.Color(255, 204, 204));
        numberLabel.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        numberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberLabel.setText("0");

        seedEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedEntryActionPerformed(evt);
            }
        });

        SeedLabel.setText("Seed");

        setSeedButton.setText("Set seed");
        setSeedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSeedButtonActionPerformed(evt);
            }
        });

        nextPseudoRandomButton.setText(">>");
        nextPseudoRandomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPseudoRandomButtonActionPerformed(evt);
            }
        });

        previousPseudoRandom.setText("<<");
        previousPseudoRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPseudoRandomActionPerformed(evt);
            }
        });

        TitleLable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TitleLable.setText("Pseudo Random Number Sequence Generator");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("using the Linear Congruential Generator algorithm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seedEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(setSeedButton)
                        .addGap(18, 18, 18)
                        .addComponent(previousPseudoRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextPseudoRandomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TitleLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SeedLabel)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numberLabel)
                .addGap(60, 60, 60)
                .addComponent(SeedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seedEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setSeedButton)
                    .addComponent(previousPseudoRandom)
                    .addComponent(nextPseudoRandomButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seedEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seedEntryActionPerformed

    private void setSeedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSeedButtonActionPerformed
        // TODO add your handling code here:
        try {
            
            this.history.empty();
            
            int newSeed = Integer.valueOf(this.seedEntry.getText());        
            this.originator.setCurrentPseudoRandom(newSeed);

            Memento snapshot = this.originator.save();       
            this.history.push(snapshot);

            this.setNumberLabel();
                        
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
            this.numberLabel.setText("sea imbecil");
        }                
    }//GEN-LAST:event_setSeedButtonActionPerformed

    private void previousPseudoRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPseudoRandomActionPerformed
        // TODO add your handling code here:                      
        try {
            this.originator.setCurrentPseudoRandom(this.history.pop().getCurrentPseudoRandom());
            this.setNumberLabel();              
        }
        catch (Exception e) {
            System.out.println(e.getMessage());
            this.numberLabel.setText(this.originator.getCurrentPseudoRandom()+"");
        }   
        System.out.println(this.history);
        
        
    }//GEN-LAST:event_previousPseudoRandomActionPerformed

    private void nextPseudoRandomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPseudoRandomButtonActionPerformed
        // TODO add your handling code here:
        
        Memento snapshot = this.originator.save();       
        this.history.push(snapshot);           
        this.originator.nextPseudoRandom();     
        this.setNumberLabel();
        System.out.println(this.history);
      
    }//GEN-LAST:event_nextPseudoRandomButtonActionPerformed

    private void setNumberLabel(){
        this.numberLabel.setText(this.originator.getCurrentPseudoRandom()+"");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SeedLabel;
    private javax.swing.JLabel TitleLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextPseudoRandomButton;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JButton previousPseudoRandom;
    private javax.swing.JTextField seedEntry;
    private javax.swing.JButton setSeedButton;
    // End of variables declaration//GEN-END:variables
    
    private PseudoRandomGenerator originator;
    private Stack<Memento> history;

    
}
